"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class input_t(object):
    __slots__ = ["player", "motion"]

    __typenames__ = ["int16_t", "string"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.player = 0
        self.motion = ""

    def encode(self):
        buf = BytesIO()
        buf.write(input_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">h", self.player))
        __motion_encoded = self.motion.encode('utf-8')
        buf.write(struct.pack('>I', len(__motion_encoded)+1))
        buf.write(__motion_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != input_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return input_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = input_t()
        self.player = struct.unpack(">h", buf.read(2))[0]
        __motion_len = struct.unpack('>I', buf.read(4))[0]
        self.motion = buf.read(__motion_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if input_t in parents: return 0
        tmphash = (0xd758737ead06814b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if input_t._packed_fingerprint is None:
            input_t._packed_fingerprint = struct.pack(">Q", input_t._get_hash_recursive([]))
        return input_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

